eureka:
  instance:
    hostname: discovery-service-recommendatory-arthrospore.apps.liquidapplicationstudio.com
    nonSecurePort: 80
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    leaseRenewalIntervalInSeconds: 5
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: https://discovery-service-recommendatory-arthrospore.apps.liquidapplicationstudio.com/eureka/
